### ISSUE TITLE
使用中发现代码中有两处可能存在问题

### ISSUE THREAD

**Issue by Bpazy** [wvdon/netease_down#1]
1. 这里是否应该应该替换成`self.url = "https://music.163.com/playlist?id="+self.url`，否则就不是歌单而是榜单了
https://github.com/wvdon/netease_down/blob/e462ed2c10730f8bff0d4ffd7b29d040a6867a9c/netease.py#L11

2. 这里也需要考虑下文件名的合法性，如：`path = path1+str(name).replace('/', '').replace('?', '')`
https://github.com/wvdon/netease_down/blob/e462ed2c10730f8bff0d4ffd7b29d040a6867a9c/netease.py#L39

**Comment by wvdon** [comment]
你好
    非常高兴收到github第一个pull,,感谢你提出的问题，我已经做出来修改。
    有机会多多交流。
    祝
好



（吴卫东）mail@wvdon.com
 
发件人： ZiYuan
发送时间： 2019-10-20 16:14
收件人： wvdon/netease_down
抄送： Subscribed
主题： [wvdon/netease_down] 使用中发现代码中有两处可能存在问题 (#1)
这里是否应该应该替换成self.url = "https://music.163.com/playlist?id="+self.url，否则就不是歌单而是榜单了
https://github.com/wvdon/netease_down/blob/e462ed2c10730f8bff0d4ffd7b29d040a6867a9c/netease.py#L11
这里也需要考虑下文件名的合法性，如：path = path1+str(name).replace('/', '').replace('?', '')
https://github.com/wvdon/netease_down/blob/e462ed2c10730f8bff0d4ffd7b29d040a6867a9c/netease.py#L39
